//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MsiClassicModePlugin.CCNet {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdatesServiceSoap", Namespace="http://www.microarea.it/PAASUpdates/")]
    public partial class UpdatesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUpdatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOfficialBuildsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNightlyBuildsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UpdatesService() {
            this.Url = global::MsiClassicModePlugin.Properties.Settings.Default.plgnMsiClassicMode_it_microarea_www_UpdatesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUpdatesCompletedEventHandler GetUpdatesCompleted;
        
        /// <remarks/>
        public event GetOfficialBuildsCompletedEventHandler GetOfficialBuildsCompleted;
        
        /// <remarks/>
        public event GetNightlyBuildsCompletedEventHandler GetNightlyBuildsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.microarea.it/PAASUpdates/GetUpdates", RequestNamespace="http://www.microarea.it/PAASUpdates/", ResponseNamespace="http://www.microarea.it/PAASUpdates/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUpdatesResponse GetUpdates(GetUpdatesRequest request) {
            object[] results = this.Invoke("GetUpdates", new object[] {
                        request});
            return ((GetUpdatesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdatesAsync(GetUpdatesRequest request) {
            this.GetUpdatesAsync(request, null);
        }
        
        /// <remarks/>
        public void GetUpdatesAsync(GetUpdatesRequest request, object userState) {
            if ((this.GetUpdatesOperationCompleted == null)) {
                this.GetUpdatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdatesOperationCompleted);
            }
            this.InvokeAsync("GetUpdates", new object[] {
                        request}, this.GetUpdatesOperationCompleted, userState);
        }
        
        private void OnGetUpdatesOperationCompleted(object arg) {
            if ((this.GetUpdatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdatesCompleted(this, new GetUpdatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.microarea.it/PAASUpdates/GetOfficialBuilds", RequestNamespace="http://www.microarea.it/PAASUpdates/", ResponseNamespace="http://www.microarea.it/PAASUpdates/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUpdatesResponse[] GetOfficialBuilds(GetUpdatesRequest request) {
            object[] results = this.Invoke("GetOfficialBuilds", new object[] {
                        request});
            return ((GetUpdatesResponse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOfficialBuildsAsync(GetUpdatesRequest request) {
            this.GetOfficialBuildsAsync(request, null);
        }
        
        /// <remarks/>
        public void GetOfficialBuildsAsync(GetUpdatesRequest request, object userState) {
            if ((this.GetOfficialBuildsOperationCompleted == null)) {
                this.GetOfficialBuildsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOfficialBuildsOperationCompleted);
            }
            this.InvokeAsync("GetOfficialBuilds", new object[] {
                        request}, this.GetOfficialBuildsOperationCompleted, userState);
        }
        
        private void OnGetOfficialBuildsOperationCompleted(object arg) {
            if ((this.GetOfficialBuildsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOfficialBuildsCompleted(this, new GetOfficialBuildsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.microarea.it/PAASUpdates/GetNightlyBuilds", RequestNamespace="http://www.microarea.it/PAASUpdates/", ResponseNamespace="http://www.microarea.it/PAASUpdates/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NightlyBuildsResult[] GetNightlyBuilds() {
            object[] results = this.Invoke("GetNightlyBuilds", new object[0]);
            return ((NightlyBuildsResult[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNightlyBuildsAsync() {
            this.GetNightlyBuildsAsync(null);
        }
        
        /// <remarks/>
        public void GetNightlyBuildsAsync(object userState) {
            if ((this.GetNightlyBuildsOperationCompleted == null)) {
                this.GetNightlyBuildsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNightlyBuildsOperationCompleted);
            }
            this.InvokeAsync("GetNightlyBuilds", new object[0], this.GetNightlyBuildsOperationCompleted, userState);
        }
        
        private void OnGetNightlyBuildsOperationCompleted(object arg) {
            if ((this.GetNightlyBuildsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNightlyBuildsCompleted(this, new GetNightlyBuildsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microarea.it/PAASUpdates/")]
    public partial class GetUpdatesRequest {
        
        private string declaredVersionField;
        
        private string productSignatureField;
        
        /// <remarks/>
        public string DeclaredVersion {
            get {
                return this.declaredVersionField;
            }
            set {
                this.declaredVersionField = value;
            }
        }
        
        /// <remarks/>
        public string ProductSignature {
            get {
                return this.productSignatureField;
            }
            set {
                this.productSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microarea.it/PAASUpdates/")]
    public partial class NightlyBuildsResult {
        
        private string fileNameField;
        
        private string filePathField;
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microarea.it/PAASUpdates/")]
    public partial class GetUpdatesResponse {
        
        private string downloadUriField;
        
        private bool updatesAvailableField;
        
        private string msiFileNameField;
        
        /// <remarks/>
        public string DownloadUri {
            get {
                return this.downloadUriField;
            }
            set {
                this.downloadUriField = value;
            }
        }
        
        /// <remarks/>
        public bool UpdatesAvailable {
            get {
                return this.updatesAvailableField;
            }
            set {
                this.updatesAvailableField = value;
            }
        }
        
        /// <remarks/>
        public string MsiFileName {
            get {
                return this.msiFileNameField;
            }
            set {
                this.msiFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetUpdatesCompletedEventHandler(object sender, GetUpdatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUpdatesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUpdatesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetOfficialBuildsCompletedEventHandler(object sender, GetOfficialBuildsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOfficialBuildsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOfficialBuildsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUpdatesResponse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUpdatesResponse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetNightlyBuildsCompletedEventHandler(object sender, GetNightlyBuildsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNightlyBuildsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNightlyBuildsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NightlyBuildsResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NightlyBuildsResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591