//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Microarea.Mago4Butler.AutomaticUpdates {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microarea.it/butler")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microarea.it/butler", IsNullable=false)]
    public partial class updates {
        
        private update[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("update")]
        public update[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microarea.it/butler")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microarea.it/butler", IsNullable=false)]
    public partial class update {
        
        private fileName[] fileNamesField;
        
        private string nameField;
        
        private type typeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fileName", IsNullable=false)]
        public fileName[] fileNames {
            get {
                return this.fileNamesField;
            }
            set {
                this.fileNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public type type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microarea.it/butler")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microarea.it/butler", IsNullable=false)]
    public partial class fileName {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microarea.it/butler")]
    public enum type {
        
        /// <remarks/>
        msi,
        
        /// <remarks/>
        dll,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microarea.it/butler")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microarea.it/butler", IsNullable=false)]
    public partial class fileNames {
        
        private fileName[] fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileName")]
        public fileName[] fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
}
