//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microarea.Mago4Butler.BL.PAASUpdates {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.microarea.it/PAASUpdates/", ConfigurationName="PAASUpdates.UpdatesServiceSoap")]
    public interface UpdatesServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.microarea.it/PAASUpdates/GetUpdates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesResponse GetUpdates(Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.microarea.it/PAASUpdates/GetUpdates", ReplyAction="*")]
        System.Threading.Tasks.Task<Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesResponse> GetUpdatesAsync(Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microarea.it/PAASUpdates/")]
    public partial class GetUpdatesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string declaredVersionField;
        
        private string productSignatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeclaredVersion {
            get {
                return this.declaredVersionField;
            }
            set {
                this.declaredVersionField = value;
                this.RaisePropertyChanged("DeclaredVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductSignature {
            get {
                return this.productSignatureField;
            }
            set {
                this.productSignatureField = value;
                this.RaisePropertyChanged("ProductSignature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microarea.it/PAASUpdates/")]
    public partial class GetUpdatesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string downloadUriField;
        
        private bool updatesAvailableField;
        
        private string msiFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DownloadUri {
            get {
                return this.downloadUriField;
            }
            set {
                this.downloadUriField = value;
                this.RaisePropertyChanged("DownloadUri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool UpdatesAvailable {
            get {
                return this.updatesAvailableField;
            }
            set {
                this.updatesAvailableField = value;
                this.RaisePropertyChanged("UpdatesAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsiFileName {
            get {
                return this.msiFileNameField;
            }
            set {
                this.msiFileNameField = value;
                this.RaisePropertyChanged("MsiFileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdatesServiceSoapChannel : Microarea.Mago4Butler.BL.PAASUpdates.UpdatesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatesServiceSoapClient : System.ServiceModel.ClientBase<Microarea.Mago4Butler.BL.PAASUpdates.UpdatesServiceSoap>, Microarea.Mago4Butler.BL.PAASUpdates.UpdatesServiceSoap {
        
        public UpdatesServiceSoapClient() {
        }
        
        public UpdatesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdatesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdatesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdatesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesResponse GetUpdates(Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesRequest request) {
            return base.Channel.GetUpdates(request);
        }
        
        public System.Threading.Tasks.Task<Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesResponse> GetUpdatesAsync(Microarea.Mago4Butler.BL.PAASUpdates.GetUpdatesRequest request) {
            return base.Channel.GetUpdatesAsync(request);
        }
    }
}
